---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wwwdoliexpertfr/public_html/ludovicthause0/
    - /usr/bin/rsync -rv --exclude=".git" --exclude=".env" $PWD/ $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH
    - php $DEPLOYPATH/artisan migrate --force
    - php $DEPLOYPATH/artisan config:cache
    - php $DEPLOYPATH/artisan route:cache
    - php $DEPLOYPATH/artisan view:cache